version: '3.8'
services:
  Car-Rental:
    container_name: car-rental
    build: ./car-rental
    ports:
      - "8081:80"
  
  Home-Rental:
    container_name: home-rental
    build: ./home-rental
    ports:
      - "8082:80"

  Movie-Rental:
    container_name: movie-tickets
    build: ./movie-tickets
    ports:
      - "8083:80"
